name: PVPControl
version: 1.0.2-SNAPSHOT
main: com.github.hotpee.pvpcontrol.PVPControl

commands:
  pvpc:
    aliases: [pvpcontrol]
    description: Command help for AdsAutoMessage

softdepend:
  - PlaceholderAPI
  - Dantiao